### PR TITLE
This fixes #1

### LINKED ISSUE #1: fly-cssnano is completely breaking local fly (with babel@6)
`fly` fails completely when `fly-cssnano` is installed, most likely due to a breaking change in babel@6:

    192-168-0-103:test-fly ionut$ ./node_modules/.bin/fly production
    stack: 
      - TypeError: Cannot read property 'filter' of undefined
      -     at Fly.module.exports (/Volumes/Data/Work/Web/test-fly/node_modules/fly-cssnano/index.js 6:5)
      -     at /Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/fly.js 113:14
      -     at Array.forEach (native)
      -     at new Fly (/Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/fly.js 108:13)
      -     at Object.spawn$ (/Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/cli/spawn.js 38:45)
      -     at tryCatch (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 67:40)
      -     at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 315:22)
      -     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 100:21)
      -     at onFulfilled (/Volumes/Data/Work/Web/test-fly/node_modules/co/index.js 65:19)
    message: Cannot read property 'filter' of undefined

I'll get back with a simple PR in a few minutes.

### PR DESCRIPTION
**Pull request by icflorescu**

### CODE REVIEW

**Comment by ben-eb** [comment]
Thanks.

Is it possible to test this?

**Comment by icflorescu** [comment]
See #1 for a simple test scenario description. The PR should pass any test suite used for the original plugin.

**Comment by icflorescu** [comment]
Can you please pull this and publish to npm?

It's probably related to `babel-core` or `babel-runtime` loose dependencies in `fly`, but it looks like  `fly-cssnano` stopped working in any scenario - you can test it by updating `fly` to the latest version.

Using the fat arrow in that context is not a good idea anyway...

**Comment by icflorescu** [comment]
Strangely enough, I just noticed the original plugin is failing `npm run test` on Node.js 5.0. So this has nothing to do with babel - there's a problem with `this` getting rebound by the arrow function. I'm kind of wandering how did it ever work...

**Comment by ben-eb** [comment]
^ Yep, can reproduce that. Strange indeed. Sorry, I haven't had time to review the code and test before, have a big project on at the moment. :smile:

**Comment by ben-eb** [comment]
Released as `v1.1.1`.

**Comment by icflorescu** [comment]
Happens to everyone :-)
Thanks for taking the time and best of luck with your project!

**Comment by bucaran** [comment]
@ben-eb @icflorescu Thanks for fixing this :+1:

**Pull request merged**
